---
# PLAY PARA CONFIGURACAO A INSTANCIA GCP
- hosts: all
  name: Configurando instancia GCP
  remote_user: cezar.leandro25
  become: yes
  tasks:
    - name: Ajustando Timezone
      timezone:
        name: America/Sao_Paulo

# PLAY PARA CONFIGURACAO A INSTANCIA GCP
- hosts: all
  name: Configurando instancia GCP
  remote_user: cezar.leandro25
  become: yes
  tasks:
    - name: Ajustando Timezone
      timezone:
        name: America/Sao_Paulo
    - name: Instalando Apache e PHP Blog
      apt: 
         update_cache: yes
         state: present
         pkg: 
            - apache2
            - php-curl
            - php-gd
            - php-mbstring
            - php-xml
            - php-xmlrpc
            - php-soap
            - php-intl
            - php-zip
            - php
            - libapache2-mod-php
            - php-mysql
            - php-cli
            - mysql-client


    - name: Download WordPress
      get_url:
        url=https://wordpress.org/latest.tar.gz
        dest=/tmp/wordpress.tar.gz
        validate_certs=no

    - name: Desempacotando o TAR do Wordpress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/
        owner: www-data
        group: www-data
        copy: no

    - name: Configurando o Apache
      lineinfile:
        dest=/etc/apache2/sites-enabled/000-default.conf
        regexp="(.)+DocumentRoot /var/www/html"
        line="DocumentRoot /var/www/wordpress"
      notify:
        - restart apache             

  handlers:
     - name: restart apache
       service:
         name: apache2
         state: restarted